id = "effekt"
name = "Effekt"
version = "0.0.1"
schema_version = 1
authors = ["Leon Fuß <leonfuss@icloud.com>"]
description = "Provides support for the Effekt programming language in Zed."
repository = "https://github.com/leonfuss/zed_effekt"

[language_servers.effekt]
name = "effekt"
language = "Effekt"

[grammars.effekt]
repository = "https://github.com/leonfuss/tree-sitter-effekt"
commit = "39cdd16e0e7c7a12c9ff5c7cdfb4b601731f0fbb"
